# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2025.05.4
_src_path: gh:astrojuanlu/copier-pylib
author_email: hello@juanlu.space
author_name: Juan Luis Cano Rodríguez
github_org: astrojuanlu
package_name: monitor_madrid_parks
project_name: monitor-madrid-parks
short_description: Monitor Madrid parks
