name: Ingest data

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install the latest version of uv and set the python version to 3.12
      uses: astral-sh/setup-uv@v6
      with:
        python-version: 3.12
    - name: Run ingest data script
      run: uv run --frozen scripts/ingest-data.py
