name: Process data

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install the latest version of uv and set the python version to 3.12
      uses: astral-sh/setup-uv@v6
      with:
        python-version: 3.12
    - name: Run ingest data script
      run: uv run --no-dev --frozen scripts/process-data.py
      env:
        S3_BUCKET: ${{ vars.S3_BUCKET }}
        S3_ENDPOINT: ${{ vars.S3_ENDPOINT }}
        S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        S3_REGION: ${{ vars.S3_REGION }}
